### ISSUE TITLE
TreeBrowser SCSS icon not displaying

### ISSUE THREAD

**Issue by marcocadete** [geany/geany-plugins#1007]
Geany Version: 1.36
Using GTK+ v3.24.20 and GLib v2.64.3 runtime libraries
OS: KDE neon User Edition 5.19 x86_64 
Kernel: 5.4.0-45-generic
Theme: Breeze Dark [Plasma], Breeze [GTK2/3] 
Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 

![Screenshot_Geany_plugin](https://user-images.githubusercontent.com/28997066/91941762-00f11480-ecfa-11ea-8a08-a66da8fb5a0d.png)

**Comment by codebrainz** [comment]
I would guess it's caused by this:

https://github.com/geany/geany-plugins/blob/5630fabcff5e29e0b4bd25e366bf9885c6e6c886/treebrowser/src/treebrowser.c#L234

There's a bit of warning about this in [the docs](https://developer.gnome.org/gtk3/stable/gtk3-Themeable-Stock-Images.html#gtk-icon-size-lookup).

A simple fix might be to not lookup the width and to just pass `GTK_ICON_SIZE_MENU` or whatever on [the following line](https://github.com/geany/geany-plugins/blob/5630fabcff5e29e0b4bd25e366bf9885c6e6c886/treebrowser/src/treebrowser.c#L235).

**Comment by codebrainz** [comment]
@marcocadete is this Issue for the icon for SASS/SCSS being huge, or because the icon says "Sass" rather than "Scss"?

If the former, see my previous comment.

If the latter, that would be up to your icon theme, it probably uses the same icon for SCSS as SASS since [they are similar syntaxes of SASS](https://sass-lang.com/documentation/syntax) and they might even share the same MIME type. This would be totally external to Geany.

**Comment by marcocadete** [comment]
@codebrainz, the issue is that it's not showing the same icon family as the other file extensions do, e.g: .js, .css, .png. Instead it displays a pink page icon with Sass written on it. Hope I'm making sense.

**Comment by marcocadete** [comment]
It might have to do with the Breeze icon theme that ships default with KDE neon User Edition 5.19? I notice that when I change the theme icon to Oxygen the icons are different. So I'm guessing the icons are not coming from Geany but the theme itself. So I guess this issue can be closed.
