### ISSUE TITLE
4 mistakes in spellcheck

### ISSUE THREAD

**Issue by ralf3u** [geany/geany-plugins#1035]
mistake 1
reproduce:
geany is opened; a document is opened; the spellcheck-symbol is deactivated in the symbol-bar;
click spellcheck-symbol; some words are marked;
now close geany; reopen the document; document appears in geany; spellcheck-symbol is still activated;
problem:
words are not marked although spellcheck-symbol is activated; the spellcheck-symbol need to be clicked 2x to let appear the markings;
possible solution:
if spellcheck-symbol is activated, then the markings should be visible

mistake 2
reproduce:
geany is opened; a document is opened; the spellcheck-symbol is deactivated in the symbol-bar;
now use the shortcut "execute spellcheck" (or something like that; I don't use the English version);
problem: 
the shortcut works but the spellcheck-symbol stays deactivated;
possible solution:
spellcheck-symbol should also be activated

mistake 3
reproduce:
geany is opened; a document is opened; the spellcheck-symbol is deactivated in the symbol-bar;
in the text are some lines with some mistakes;
press the shortcut "spellcheck on/off" (or something like that; I don't use the English version);
problems:
there is no spellcheck at all;
go in the middle of the text and type some wrong words; only the current line will be checked; lines before and after will not be checked;
possible solution:
the shortcut should have exactly the same behavior like the spellcheck-symbol: check ALL text of the document right away;
reason: every time the shortcut "spellcheck on/off" is pressed, the spellcheck-symbol changes in on/off

mistake 4
reproduce:
geany is opened; a document is opened; the spellcheck-symbol is deactivated in the symbol-bar;
press the shortcut "spellcheck on/off" (or something like that; I don't use the English version);
now write some wrong words; press again the shortcut "spellcheck on/off"
problem:
current markings do not go away;
possible solution:
the text of the spellcheck-symbol is exactly the same like the shortcut, so they should have the same behavior: on/off of ALL markings;
reason: every time the shortcut "spellcheck on/off" is pressed, the spellcheck-symbol changes in on/off

geany version 1.36

**Comment by ralf3u** [comment]
I don't see the sense in using 2 different shortcuts for spellcheck (what can be found in the preferences of spellcheck);
one shortcut would be completely enough;
this one shortcut should have exactly the same behavior like the spellcheck-symbol of the symbol-bar

**Comment by eht16** [comment]
Each of the "mistakes" is based on a misunderstanding of the toolbar symbol: 
it is meant as a switch to enable or disable the spell checking while you are typing.
Clicking the icon is not meant as "check the document now". For this, there is the menu item and keybindings.


> mistake 1
> reproduce:
> geany is opened; a document is opened; the spellcheck-symbol is deactivated in the symbol-bar;
> click spellcheck-symbol; some words are marked;
> now close geany; reopen the document; document appears in geany; spellcheck-symbol is still activated;
> problem:
> words are not marked although spellcheck-symbol is activated; the spellcheck-symbol need to be clicked 2x to let appear the markings;
> possible solution:
> if spellcheck-symbol is activated, then the markings should be visible

It seems to be related to the misunderstanding explained above.
There is an option in the plugin preferences to enable checking documents when they are opened.
This probably comes close to what you expected. Be aware, if you start Geany with a couple of documents
opened from the last session, those documents will not be checked.


> mistake 2
> reproduce:
> geany is opened; a document is opened; the spellcheck-symbol is deactivated in the symbol-bar;
> now use the shortcut "execute spellcheck" (or something like that; I don't use the English version);
> problem:
> the shortcut works but the spellcheck-symbol stays deactivated;
> possible solution:
> spellcheck-symbol should also be activated

It seems to be related to the misunderstanding explained above.


> mistake 3
> reproduce:
> geany is opened; a document is opened; the spellcheck-symbol is deactivated in the symbol-bar;
> in the text are some lines with some mistakes;
> press the shortcut "spellcheck on/off" (or something like that; I don't use the English version);
> problems:
> there is no spellcheck at all;
> go in the middle of the text and type some wrong words; only the current line will be checked; lines before and after will not be checked;
> possible solution:
> the shortcut should have exactly the same behavior like the spellcheck-symbol: check ALL text of the document right away;
> reason: every time the shortcut "spellcheck on/off" is pressed, the spellcheck-symbol changes in on/off

It seems to be related to the misunderstanding explained above.
This is intended behaviour, toggling the "spellcheck while typing" feature does **not** trigger a full recheck of the document but only for these lines which were touched since toggling on.

 
> mistake 4
> reproduce:
> geany is opened; a document is opened; the spellcheck-symbol is deactivated in the symbol-bar;
> press the shortcut "spellcheck on/off" (or something like that; I don't use the English version);
> now write some wrong words; press again the shortcut "spellcheck on/off"
> problem:
> current markings do not go away;
> possible solution:
> the text of the spellcheck-symbol is exactly the same like the shortcut, so they should have the same behavior: on/off of ALL markings;
> reason: every time the shortcut "spellcheck on/off" is pressed, the spellcheck-symbol changes in on/off

It seems to be related to the misunderstanding explained above.
The "spellcheck while typing" is not meant as toggling the spellcheck feature completely but only the automatic checking while typing. This is intended behaviour.
If you want to have just the error markers being removed, use "Document -> Remove error indicators" (there are also keybindings available).

**Comment by ralf3u** [comment]
in Geany 1.37.1:
- open Geany with no document open
- in the tool-bar: check that the spellcheck-symbol is deactivated
- open a txt-document with some wrong written words in Geany
- in the tool-bar: activate the spellcheck-symbol
result: words are red underlined
- close Geany
- reopen a txt-document with some wrong written words in Geany
- the spellcheck-symbol is activated although no words are red underlined

**Comment by ralf3u** [comment]
@eht16 
to mistake 1 you write:
> Be aware, if you start Geany with a couple of documents opened from the last session, those documents will not be checked.

That's a pity, because after a start of Geany I need always to click 2 times the spellcheck-symbol FOR EACH document to see the errors. Is there really no way that those documents are checked automatically after a start of Geany?

Even the big office-suite LibreOffice doesn't have something like "spellcheck while typing", because it is not necessary for the most people.

Instead of a "spellcheck while typing"-symbol in the tool-bar, I would prefer a "spellcheck on/off"-symbol that should work exactly like "Automatic Spell Checking" in LibreOffice 7.1.3..2  (what works in LibreOffice with the shortcut shift+F7).

**Comment by eht16** [comment]
> @eht16
> to mistake 1 you write:
> 
> > Be aware, if you start Geany with a couple of documents opened from the last session, those documents will not be checked.
> 
> That's a pity, because after a start of Geany I need always to click 2 times the spellcheck-symbol FOR EACH document to see the errors. Is there really no way that those documents are checked automatically after a start of Geany?

Technically this is possible but not yet implemented because it can cause a significant startup delay if there many documents open in a session which have to be all checked at startup.
I see your use case but it might different for many users.

Of course, there could be an option to make this behaviour configurable.

 
> Even the big office-suite LibreOffice doesn't have something like "spellcheck while typing", because it is not necessary for the most people.

Because LibreOffice is a word processing tool while Geany is primarly an IDE. With LibreOffice, users usually write text and with Geany mostly code and code doesn't need spell checking, at least not to the same extend as written text. So, you cannot directly compare LibreOffice to Geany, they are different tools with different scopes.


> Instead of a "spellcheck while typing"-symbol in the tool-bar, I would prefer a "spellcheck on/off"-symbol that should work exactly like "Automatic Spell Checking" in LibreOffice 7.1.3..2 (what works in LibreOffice with the shortcut shift+F7).

I see. It's completely possible to implemented. As above, it needs someone to do it.
It's unlikely I'll find time for this in the next weeks :(.

It might help to open a new issue with a clear feature request for an option to check session files on startup and a general toggle spellcheck toolbar button. So interested people can find the requirements easily without reading through this rather long issue. What do you think?

**Comment by ralf3u** [comment]
@eht16
> It might help to open a new issue with a clear feature request for an option to check session files on startup and a general toggle spellcheck toolbar button. So interested people can find the requirements easily without reading through this rather long issue. What do you think?

good idea; I just opened #1090, so you can close the issue-number 1035
