### ISSUE TITLE
git-changebar depends on libgit2-26 but is not installable on mint 20 || ubuntu 20.04

### ISSUE THREAD

**Issue by micdech** [geany/geany-plugins#1047]
on mint repository (and maybe also ubuntu 20.04) libgit is available only on 0.28 version. 
git changebar show it is impossible to install due to libgitversion <=26 (?!)

Can we make something for this?

**Comment by elextr** [comment]
This is a packaging issue.  The Geany project does not do the packaging for any distro.

Just FTR my Mint 20 says libgit2 0.28.4 and git-changebar requiring >= 0.28.1 so it should work.

**Comment by b4n** [comment]
Well, I myself am not sure what the issue is :)
@micdech could you give more details, e.g. show the actual error message you get, and the steps leading you there?  As @elextr said if it's your distribution's packages we don't make those and don't have control over them, but if you're building from sources maybe we got a check wrong or something.  In any case, IIUC the plugin should still supports libgit2 0.28.

**Comment by micdech** [comment]
Thankyou b4n for your reply. Unfortunately due to maintenance of apps, i prefer to install this via repo (sometimes PPA) debian based distro.

I used PPA ubuntu for geany 1.37 using mint 20 as a distro. 

Result i have to update my repo to brand new repo 21.04 to get new version of the geany common and geany plugins.

Now my issue is over, but the problem is in oldest repositories...

Thank you again for your support
