### ISSUE TITLE
GeanyVC git commit not working (Windows)

### ISSUE THREAD

**Issue by Morusec** [geany/geany-plugins#1056]
Hi!

I usually use the plugins under Linux and everything works as expected. 
Recently, I've been dual booting on Windows and can't get the "git commit" from GeanyVC to work at all. 

I can check files, add a comment and click "Commit" but it fails with this error:
"17:39:18: Error initializing GeanyVC spell checking: enchant error for language: en. Check your configuration."

I also can see this under Debug Messages:
17:39:18: (NULL) WARNING	: Error loading plugin: 'C:\Program Files (x86)\Geany/lib/enchant-2\enchant_aspell.dll': The specified module could not be found.
17:39:18: (NULL) WARNING	: Error loading plugin: 'C:\Program Files (x86)\Geany/lib/enchant-2\enchant_voikko.dll': The specified module could not be found.

The DLL files are present if that path with slashes and backslashes can be interpreted right.

I did not enable any other plugins than "GeanyVC" and "Git Change Bar" so no spellchecking should be considered. 
I suspects it is related to "gtkspell -- GeanyVC's spell-check support"

I am used to recompile and test under linux but have no clue how to do it right under Windows. 

Thank you!

Julien

**Comment by nomadbyte** [comment]
Which Geany version are you using? How did you install it?

GeanyVC plugin is dependent on `libgtkspell`, which in its turn depends on `libenchant`. The spellcheck is used for the commit message/comment (when language is configured in the plugin's Preferences).

**Comment by eht16** [comment]
@Morusec did you try to disable spellchecking for GeanyVC by setting the language option to an empty string in the plugin preferences?

The posted warnings about aspell and voikkpo libraries are rather harmless and I even think the mixed slashes would work. But Enchant on Windows doesn't work with these libraries even if there are built and present, these two messages always appear and I didn't find a way yet to silence them.

I assume the real problem is that you simply doesn't have any dictionaries installed but spell checking configured in the plugin preferences.

**Comment by Morusec** [comment]
The Windows version 1.37.1 was installed along side with geany-plugins 1.37. 
In GeanyVC's option, the field for the language option is empty by default.

The error messages a WARNINGs and should not break the git functionality, it may not be related.

**Comment by eht16** [comment]
Just tested on a Windows box: I can confirm the commit action fails. But it is unrelated to any spell checking issues.
Though we also cannot see why it is failing at all, the plugin doesn't log the process result :(. For this to work, we need https://github.com/geany/geany-plugins/pull/1026 to be merged.

Also, the message "17:39:18: Error initializing GeanyVC spell checking: enchant error for language: en. Check your configuration.` is quite misleading I'd say as it also happens when no spell check language is selected in the plugin preferences (as you said).
@frlan I'd say the plugin should either have a toggle to enable/disable spell checking at all or at least disable spell checking when the language field is empty (currently it seems to default to "en" if it is empty).

So, we have two issues here: the failing `git commit` command without any feedback and the spell checking errors even if not enabled.

**Comment by eht16** [comment]
Running `geany -v` revealed the underlying GIT error:
```
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'enrico@DESKTOP-1921KWH.(none)')
```
So, in my case the GIT repository wasn't configured properly.
After setting author, the `git commit` worked successfully.

**Comment by Morusec** [comment]
Nice find!
My settings were set globally and are not considered for some reason.

When settings them per project, it works!

Thank you
