### ISSUE TITLE
Сan't find the package geany-plugin-webhelper from repository

### ISSUE THREAD

**Issue by pofart** [geany/geany-plugins#1066]
Hello, I can't find the package geany-plugin-webhelper, after install all plugins from terminal cant find webhelper, of course i maybe install from source but I would like to know the reason why it is not in the repositories of both distributions (Parrot OS and Elementary OS).
Thank`s for help! :)

**Comment by elextr** [comment]
The Geany project does not make repository packages, you need to ask the particular distro, possibly it doesn't provide some dependency of webhelper, but the packager should know.

**Comment by eht16** [comment]
This is probably because Geany, and so Geany-Plugins as well, are built against GTK3. The Webhelper plugin needs a WebkitGTK library compatible with GTK3 and such a packages does not exist in Debian (and so also in Parrot OS and probably also not in Elementary OS).

Anyway, we cannot do anything about this. Please report this to your distribution packagers, as @elextr said.
