### ISSUE TITLE
Spell Check can’t be turned off with a shortcut

### ISSUE THREAD

**Issue by ralf3u** [geany/geany-plugins#1156]
Spell Check can be turned on with a shortcut, but it can’t be turned off with a shortcut. In the list of shortcuts there is "Run Spell Check". It would be good if it would be replaced by something like "Spell Check on/off" or rather "Toggle Spell Check", so one can toggle the feature with just one shortcut.

Steps to reproduce
Try to turn Spell Check on and off with a shortcut.

Actual result
Spell Check can be turned on with a shortcut but it can’t be turned off with a shortcut. Even with the shortcut "Toggle Check while Typing" Spell Check can't be turned off.

Comparison
In LibreOffice 7.1.3.2 "Automatic Spell Checking" can be turned on and off with the same shortcut (Shift+F7).

Remark
I use Geany without toolbar. So every time I want to turn off Spell Check, I have to do always those 3 steps:
1 make the toolbar visible
2 click on the Spell-Check-symbol in the toolbar
3 let disappear the toolbar

**Comment by eht16** [comment]
The shortcut "Run Spell Check" triggers the a one-time check of the current document. It is not intended and won't be changed to configure a setting or toggle anything on/off.

The shortcut "Toggle Spell Check While Typing" does what it says: it does toggle the setting "check while typing" on and off. I guess this is what you want. Otherwise I'm not sure what exactly you expect.

**Comment by ralf3u** [comment]
@eht16 

> Otherwise I'm not sure what exactly you expect.

Sometimes I would like to see the text without red underlines. And to turn off the red underlines, there is no shortcut for that. So again, what about the idea to change "Run Spell Check" to something like "Spell Check on/off" or rather "Toggle Spell Check", and of course to reprogram this shortcut, so that it can be toggled, like this is the case in LibreOffice 7.1.3.2? If this statement does not provide clarity, please let it me know.

**Comment by eht16** [comment]
Ok, so you basically want to remove the red underlines after the check has been ran?
You can use the "Remove Error Markers" keybinding, also available as menu item in the Document menu.

**Comment by ralf3u** [comment]
>You can use the "Remove Error Markers" keybinding, also available as menu item in the Document menu.

Yes, that's right. But a shortcut would be much better, specially when a user disabled the menu-bar like me. I mean, why you offer a toggle-version for "Check while Typing", but not for "Run Spell Check"?

**Comment by eht16** [comment]
> > You can use the "Remove Error Markers" keybinding, also available as menu item in the Document menu.
> 
> Yes, that's right. But a shortcut would be much better, 

 "Remove Error Markers" keybinding is a keybinding! Find it in the Preferences dialog under Keybindings in the "Document" section.

 I mean, why you offer a toggle-version for "Check while Typing", but not for "Run Spell Check"?

As said above, because  "Run Spell Check" is an action to execute and not a state that could be toggled.

**Comment by ralf3u** [comment]
>"Remove Error Markers" keybinding is a keybinding! Find it in the Preferences dialog under Keybindings in the "Document" section.

Sorry, you are right. But then I need another shortcut, because I can't take the same shortcut like "Run Spell Check". So, I can not toggle. To toggle is more comfortable than to use two different shortcuts.
