### ISSUE TITLE
Outdated gpgme.m4 is blocking Debian package migration

### ISSUE THREAD

**Issue by rdipardo** [geany/geany-plugins#1213]
According to [Debian's bug tracker]:

> geany-plugins ships [an outdated version of gpgme.m4][0] which cannot handle the transition from gpgme-config to [gpgrt-config].

Apparently the stale macros can be simply pruned out with no impact on the build: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1024483;filename=remove-outdated-gpgme.m4.diff;msg=5

But given the proposal to [drop geany-plugins from distribution][1], it seems Debian is expecting a dependency migration to libgpg-error-dev, with updated macros conforming to the gpgrt spec.

There are examples around the Web that might be copied/adapted, e.g.,

- [GPGME](https://dev.gnupg.org/rMf9cbf2c8a839d2c3df20157cfe65b67a4b0bcb5a)
- [libgpg-error (unofficial fork)](https://github.com/ShiftMediaProject/libgpg-error/blob/master/src/gpgrt.m4)

The proper division of package maintenance roles is still mostly a mystery to me. This is just a heads-up, in case anything can be done from Geany's end.

[Debian's bug tracker]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1024483
[gpgrt-config]: https://manpages.debian.org/testing/libgpg-error-dev/gpgrt-config.1.en.html
[0]: https://github.com/geany/geany-plugins/blob/0fd74d766f231e2aa84ca67af4da4773552eceb6/build/bundled/gpgme.m4#L1
[1]: https://tracker.debian.org/pkg/geany-plugins#:~:text=Version%201.38%2Bdfsg%2D1.1%20of%20geany%2Dplugins%20is%20marked%20for%20autoremoval%20from%20testing%20on%20Mon%2019%20Dec%202022.

**Comment by elextr** [comment]
@hyperair as the Debian package maker, and the one who bundled gpgme.m4?

**Comment by hyperair** [comment]
Thanks for the ping, looks like I missed the Debian bug report.

I think I added it years ago in https://github.com/geany/geany-plugins/commit/2535603ae1a211d68d5f2f1122fb5e8972e0b754 to avoid a hard dependency on `gpgme.m4` being present in the system generating the `dist` tarball, because that would result in a dist tarball that is unable to enable `geanypg` via `./configure` without rerunning `./autogen.sh`.

I'll deal with the Debian side of things with a downstream patch first since the deadline is in 4 days, then I'll see if updating our bundled `gpgme.m4` will fix things.
