### ISSUE TITLE
Compiling geangy-plugins appeared errors

### ISSUE THREAD

**Issue by Novak-Zhao** [geany/geany-plugins#1255]
I  use msys2 to compile geany-plugin-1.38 source code ;when I excute "make j2" in msys2 ;it shows:
"collect2.exe:error :ld return 1 exit status " "make[2]: *** [makefile:762:viw.exe] Error 1";
I want to know how to solve it

**Comment by eht16** [comment]
@Novak-Zhao contacted me via mail additionally and after updating my MSYS2 environment to the latest packages, I can reproduce the problem.
So I assume something has changed which triggers the build errors.

I'm not completely sure whether I have read the log correctly, to me it seems it fails at linking in the vimode plugin. Though I have no clue why it complains about all the missing C++ symbols.

Has anyone an idea what could cause this?

Full build log (linker errors start at line 10652):
https://gist.github.com/eht16/5b5ca97557c667a7a97e511b05677b8c/raw/81a221fbe9a5ac37b852568191afd1b5585aef70/full_build.log

List of installed MSYS2 packages:
https://gist.github.com/eht16/5b5ca97557c667a7a97e511b05677b8c#file-msys2-packages

@Novak-Zhao running `./configure --disable-vimode ...` fixes the build, obviously the Vimode plugin will not be available then.

**Comment by elextr** [comment]
It sort of looks like what you get when C++ code is linked with the C library, not the C++ library.  I expect the collect2 failed because of the undefined C++ symbols.

**Comment by elextr** [comment]
Geany is configured as a C++ entity, for example see line 1265 for `libgeany` or 1282 for `geany.exe` of the log, `--tag=CXX` and it runs `ccache g++`.  All the plugins are C, for example `autoclose` at line 4771 has `tag=CC` and runs `ccache gcc` and they work ok.

But it looks like vimode uses more of Scintilla than other plugins and so it needs to be treated as C++, not C as it is at line 10650 (`--tag=CC` and `ccache gcc`).  Note its the only plugin that explicitly includes `ScintillaWidget.h` and defines its own SSM, all others plugins I checked use Geany's SSM, so maybe that causes issues with something that changed in MSYS2.

**Comment by elextr** [comment]
Oh yeah, forgot to ping @techee :grin:

**Comment by techee** [comment]
> Oh yeah, forgot to ping @techee 😁

Always a wise things to do, I'm in a kind of dormant state otherwise ;-).

> But it looks like vimode uses more of Scintilla than other plugins and so it needs to be treated as C++, not C as it is at line 10650 (--tag=CC and ccache gcc). Note its the only plugin that explicitly includes ScintillaWidget.h and defines its own SSM, all others plugins I checked use Geany's SSM, so maybe that causes issues with something that changed in MSYS2.

Possibly good direction of thinking but I don't think it's the plugin itself which causes the error.

In addition to the plugin, I build a separate binary `viw` (vi worsened) which in theory is completely independent of Geany and doesn't use any of the Geany's APIs (basically while implementing the plugin, I realized I'm more or less building a separate editor which could be a base for any vi-mode-based editor using Scintilla). `viw` is such a sample editor - I just need Scintilla for it to work - I could have made a copy of Scintilla to the plugin source tree but since it's already part of Geany, I link against libgeany and use Scintilla from there:

https://github.com/geany/geany-plugins/blob/5b8bf656d90260779eb98933c0489c77681439e7/vimode/src/Makefile.am#L46-L48

https://github.com/geany/geany-plugins/blob/5b8bf656d90260779eb98933c0489c77681439e7/vimode/src/Makefile.am#L55-L58

So I think this should be changed (not sure how) so it's compiled as a C++ binary, right?

**Comment by elextr** [comment]
> I link against libgeany and use Scintilla from there:

Line 10654 for example shows the link errors are in Scintilla looking for the C++ system library exception handling code.  Presumably libgeany by itself doesn't resolve those because it assumes it will dynamically link with the C++ runtime, but it is being linked with the C runtime.

> (not sure how)

Me neither, but [this](https://github.com/geany/geany/blob/d6ce258cec790da1e81db48476507bb114c7e482/src/Makefile.am#L130) is in Geany `Makefile.am`

**Comment by elextr** [comment]
BTW have no idea why it works on Linux and what MSYS2 may have changed to break it.

**Comment by elextr** [comment]
Or of course we could just not build viw on Windows, especially since there is a Vi for Windows called [viw](https://www.mkssoftware.com/docs/man1/viw.1.asp).

**Comment by rdipardo** [comment]
> BTW have no idea why it works on Linux and what MSYS2 may have changed to break it.

If they bumped GCC [to 13.x], the refactored standard headers might've done it: <https://gcc.gnu.org/gcc-13/porting_to.html>


[to 13.x]: https://gist.github.com/eht16/5b5ca97557c667a7a97e511b05677b8c#file-msys2-packages-L124

**Comment by techee** [comment]
> Or of course we could just not build viw on Windows, especially since there is a Vi for Windows called [viw](https://www.mkssoftware.com/docs/man1/viw.1.asp).

I just did that in #1259. @eht16 Would you test if it fixes the problem?

**Comment by elextr** [comment]
@rdipardo probably not, the problems are in linking, not in compiling.

**Comment by rdipardo** [comment]
> @rdipardo probably not, the problems are in linking, not in compiling.

Headers can provide `extern` declarations, which compile but still confound the linker, e.g.

~~~c
/*
 * undef.h
 */
extern int foo(void);
~~~

~~~c
/*
 * undef.c
 */
#include "undef.h"
int main(void)
{
   return foo();
}
~~~

~~~sh-session
$ gcc -Wall -Wextra -c undef.c
$ echo $?
0
$ gcc undef.o
/usr/bin/ld: undef.o: in function `main':
undef.c:(.text+0x5): undefined reference to `foo'
collect2: error: ld returned 1 exit status
~~~

Replacing core type definitions with `extern` declarations in dependent headers would be a pretty nasty trick on GCC's part, but not impossible.

**Comment by elextr** [comment]
It is endemic in C++ code for STL headers to be forgotten but everything worked because some other header included the one needed.  As described in the link you provided, GCC has simply removed some of those situations, now they fail without explicit inclusion.  IIRC there is an alpha standard tool based on the internals of clang and LLVM to analyse and find what headers are needed to cover all the STL calls made by any file, but well, its alpha and several projects (eg chromium) have abandoned it for now.

So the header rearrangement will result in missing declarations, so stuff will fail to compile, not excess declarations that are not in the system library (except when the C library is used instead of the C++ one, the main problem here ;-).   And so even if msys2 upgraded its gcc it still doesn't explain why in the past it linked ok, how did it previously define those C++ library internal symbols if it linked against the C library?  And why does it work on Linux.

Anyway its an intellectual exercise since @techee has removed the foreign parasitic not part of Geany tool build from the Windows build.  And now we know, so when it fails on Linux we can jump in and point fingers immediately ;-)

**Comment by eht16** [comment]
@Novak-Zhao you can use the changes from https://github.com/geany/geany-plugins/pull/1259 to fix the build.
E.g. by downloading the changes as patch from https://github.com/geany/geany-plugins/pull/1259.patch and then apply it locally, should work with the 1.38 sources as well.
