### ISSUE TITLE
SVG and X3D markup languages

### ISSUE THREAD

**Issue by anonimo82** [geany/geany-plugins#1313]
Hello you all B)

I'd like to use Geany to write SVG and X3D markups, is it there any way to add support for them?

Thanks for any help, have a nice day ^.^

**Comment by elextr** [comment]
Just the generic XML features.  You could add the extensions of those files to the XML type in `filetype_extensions.conf` by `Tools->Configuration Files->filetype_extensions.conf` so the XML filetype will be set automatically.

**Comment by anonimo82** [comment]
Excuse me, I didn't understand

**Comment by elextr** [comment]
There is no specific support for SVG or X3D, but there is generic support for XML, which is what SVG is.  Not sure about X3D, but wikipedia says its "inetgrated with XML" whatever that means.  So possibly the XML support will help you with them, so if you open the svg file and set the document->filetype to XML you should at least get useful(ish) XML highlighting.

To make it automatically choose XML when opening say svg files you need to add that to the extensions listed for XML.  Since you are using such an olde version the menu command I gave probably isn't available and you will have to edit and copy the file directly, see the manual appropriate to your version.

**Comment by anonimo82** [comment]
I see, thanks anyhow. Maybe I'll do some homework later with the manual and the plugins you pointed me to.
