### ISSUE TITLE
[Geanylua] geany.choose doesn't list all files

### ISSUE THREAD

**Issue by Johnmcenroyy** [geany/geany-plugins#1374]
There is an example:
https://github.com/geany/geany-plugins/blob/master/geanylua/examples/info/list-open-files.lua

It gets info about all opened files in Geany and open this list in new tab of Geany or lists them in choose menu.
List in new tab works as expected but geany.choose function not - it lists only two first opened files.

**Comment by elextr** [comment]
Please note that Geanylua is orphaned and so unmaintained.

**Comment by Johnmcenroyy** [comment]
@elextr yes, I know but maybe someone knows why this happened, will try to find myself also, but how I understand it is better to move to Peasy plugin (just compiled) with Libpeas support. Is Geanylua planned to be removed from Geany plugins ?

**Comment by Johnmcenroyy** [comment]
Overall good simple plugin, but pity seems not all work.

**Comment by elextr** [comment]
Well clearly nobody needs it urgently enough to be willing to support it.

There is no specific policy for removing plugins from the plugins collection, in fact sometimes the threat of removal results in individual PRs to keep an almost dead plugin going (usually something like moving to a new library version as happened to Geanylua and whatever changes that needs).  But that is individual PRs, it often does not result in a rush of offers to take up ownership of the plugin.

I don't know how many geanylua issues there are, but in the past many scripts have worked just fine, guess they didn't use your troublesome function.  So that makes it even harder to let it go, even if its no longer perfect.  I suspect it will limp along until either some major issue occurs or the oldest version of lua that is provided by distros is not compatible with the newest version of lua that geanylua uses.  Or a white knight thunders in on a massive horse and takes over maintenance. :horse_racing: 

Merging Peasy to Geany-plugins is an issue because Peasy uses its own compile and build system, not Autotools.  And also if the creator does not want to include it in Geany-plugins thats entirely their right, and its not unusual.  Of course "somebody" could make a copy of Peasy and include it in Geany-plugins, thats GPL, but having done that for a plugin in the past myself, I would say its not a happy position to be, even if the originator didn't mind.

Unfortunately for Peasy it appears only Arch AUR seems to supply it as a package, not Ubuntu and dependants or Fedora (dunno about Debian, the package search is down, but its likely that Ubuntu would have it if Debian did).  So Peasy is not really an option for those who don't compile stuff even though its a technical improvement.

**Comment by Johnmcenroyy** [comment]
@elextr Ok, understood. Thanks for info. Peasy works fine in Arch, but like also Geanylua for more simplicity.

**Comment by Skif-off** [comment]
@Johnmcenroyy, how many files? I haven't noticed any such problems yet.
(I use the patch from [Issue 690](https://github.com/geany/geany-plugins/issues/690), but I'm not sure it matters.)

P.S. But `geany.activate` has [problem](https://github.com/geany/geany-plugins/pull/1234).

**Comment by Johnmcenroyy** [comment]
@Skif-off Only two files appear in choose dialog no mater how much files are opened in Geany - 3 or 7 etc.
This simple script doesn't work for me:
```
#! /usr/bin/env lua

files = {"file1","file2","file3","file4","file5"}

for i = 1, 5 do
  geany.status(files[i])
end

geany.choose("Choose your file:", files)
```
geany.status works as expected - in messages window there all files
geany.choose lists only file1 and file2

**Comment by Johnmcenroyy** [comment]
@Skif-off It seems that all files appear in Geany.choose it is just two lines always with scroll.
It seems that patch can solves it. Thanks for info.

**Comment by Johnmcenroyy** [comment]
I confirm that this https://github.com/geany/geany-plugins/issues/690#issuecomment-723503783 patch solves this issue.
