### ISSUE TITLE
Latest projects shows path instead of name

### ISSUE THREAD

**Issue by JanAxelsson** [geany/geany-plugins#1379]
I would expect to see the  _project name_ in the `Project/Latest project ` menu, but instead I see the paths to the project config file.

Showing `Project/properties`, I am allowed to enter a name for the project, but I fail to see where that name is used.
Showing the project name instead of a path and the config file name would be much more helpful

PS, I have tried to translate menu names and field names from swedish version, so I hope it makes sense

**Comment by elextr** [comment]
> Showing Project/properties, I am allowed to enter a name for the project, but I fail to see where that name is used.

If a project is open the project name is shown in `[]`s on the Geany window title bar.

**Comment by JanAxelsson** [comment]
That is nice, and I see it.  As is, I think the feedback showing the name in window title, and the path to the project config file in the menu is not giving a coherent feedback (name vs path).

It would therefore be helpful to see the name also in the list where you look for recent projects.  For my use case where I create projects using `Project/New from folder`  menu, all the project config files are in the same folder ($HOME/project), so it seems redundant that the`Recent Rroject` menu list the same folder path over and over again. 

One way to get best of both worlds could be to list _both_ the project name and the path to the project config file in the `Recent Rroject` menu, for instance like this:
`My great project name (/home/jan/project/abc.geany)`

**Comment by elextr** [comment]
> all the project config files are in the same folder ($HOME/project)

Project files can be located anywhere, many users locate the project in the project file tree, not in a users home directory.  Therefore to open a project what is needed is to the relevant project file, not to a project name, which need not be unique, and so listed recent projects are the file path which is unique, not the name.  A project open is a normal file open dialog since the file has to be located to open it, the name has no information that locates the file.  

Listing the name would require the project file to be opened and read to make an addition to the list, so its unlikely to be done that way.  Essentially names are not particular use, its just some users may need it.

**Comment by JanAxelsson** [comment]
Thanks for explaining!31 okt. 2024 kl. 01:51 skrev elextr ***@***.***>:﻿

all the project config files are in the same folder ($HOME/project)

Project files can be located anywhere, many users locate the project in the project file tree, not in a users home directory.  Therefore to open a project what is needed is to the relevant project file, not to a project name, which need not be unique, and so listed recent projects are the file path which is unique, not the name.  A project open is a normal file open dialog since the file has to be located to open it, the name has no information that locates the file.
Listing the name would require the project file to be opened and read to make an addition to the list, so its unlikely to be done that way.  Essentially names are not particular use, its just some users may need it.
