### ISSUE TITLE
git-changebar: race when quickly changing files

### ISSUE THREAD

**Issue by techee** [geany/geany-plugins#244]
There seems to be some kind of race when quickly changing files using e.g. Ctrl+Tab. When pressing Ctrl+Tab several times in a row it appears git-changebar diffs the previous file with the current file thinking it is the same file and shows the diff in the changebar.

This is a bit hard to trigger because normally the switch is too fast for this to happen. I have seen it with the linux kernel project with all the tags loaded to make Geany a little slower but maybe it's enough to have just two really big files open and cycle between them (they would have to be version-controlled of course).

**Comment by b4n** [comment]
Indeed, good catch.  Could you try the patch above (at [git-changebar/race](https://github.com/b4n/geany-plugins/commits/git-changebar/race))?  it seems to properly fix the issue here, but as I couldn't reproduce it very consistently I'd love additional testing -- although both the issue and fix make sense.

See the patch for details if you're interested on what's going on.

**Comment by techee** [comment]
Yep, this fixes the issue for me (and adding the identifier to compare documents makes sense).
