### ISSUE TITLE
./waf updatepo doesn't work

### ISSUE THREAD

**Issue by peter-scholtens** [geany/geany-plugins#293]
For some reason the ./waf updatepo script doesn't work. It complains output missing a file. The reason seems to be that (recently?) the files in multiterm are changed from .c to .vala. Simply faking the system by setting a symbolic link for each .c file in this ./multiterm/src directory let the waf script run correctly, like:

ln -s ./multiterm/src/config.vala ./multiterm/src/config.c

But that's a workaround, not a permanent solution, I think.

**Comment by frlan** [comment]
This is caused by the fact that the c files are created from the vala files. This should be solved by running ./waf build before doing ./waf updatepo (and having valac installed)

**Comment by eht16** [comment]
Nope, this is not enough. The problem is that the generated C sources are expected in the ../multiterm/src folder, relative to the POTFILES.in file.
This is not true when building with Waf because Waf puts the generated C files into `_build_/multiterm/src`.

I guess with some magic, we could fix this or work around it in some way. But since we plan to drop Waf support after the 1.26 release, I'm tempted to leave this as is for now.
I'm pretty much sure your workaround should suffice for now as the generated C files should contain the same strings as the .vala files.

**Comment by peter-scholtens** [comment]
Entering the ./multiterm/src  and running make before waf updatepo does the trick too. Indeed, if waf get replaced, don't spend time on this.
