### ISSUE TITLE
Remove deprecated Waf build support

### ISSUE THREAD

**Issue by frlan** [geany/geany-plugins#310]
Waf support needs to be removed as with 1.27 it will be deprecated: 
* waf binary
* waf configuration and plugin local scripts
* documentation update to ensure autogen is used for building plugin

**Comment by codebrainz** [comment]
Has anyone gotten Autotools working for the plugins on Windows yet?

I tried just building Geany the other day and after a few hours and several gigabytes of dependencies got it built, but it was still wholly contained inside the msys2/msys64 environment. We're going to need some serious Autotools/Pacmanfu to get everything working using alternate roots and bringing all the dependencies out of msys2 into a useful place like Windows Program Files. I imagine Geany-Plugins will be somewhat more difficult than Geany, due to the size and complexity of the Autotools.

**Comment by frlan** [comment]
At least nightly.geany.org builds are already done with autotools.

**Comment by codebrainz** [comment]
More worried about how it fares in the simulated *nix msys environment. I've never built GP on Windows using any build system, maybe it won't be as bad as I assume. At least msys has a proper package manager now.

**Comment by eht16** [comment]
I just built GP from GIT master on MSYS2 (including plugins depent on WebKitGTK). The only problem I had was that I had to convert all build/*.m4 files to Unix line endings, otherwise automake got into trouble. I guess we can enforce this via a .gitattributes files with something like `*.m4 text eol=lf`.
Besides this, everything worked fine and without any problems.

I had to install some dependencies but these were by no means several gigabytes.
Compiling is actually slow on MSYS2, I'm not sure why, it seems to be IO related. This is a bit annoying but not a no-go, IMO.

What mostly needs to be done is to create a GTK bundle with all necessary dependencies for distribution and to adapt the Geany and GP installers.

**Comment by kugel-** [comment]
I'm working on the bundle creation script

**Comment by codebrainz** [comment]
@eht16 from raw msys2 install to being able to compile Geany it had to pull in some gigabytes (more than one at least). But that includes the toolchain and such stuff.

@kugel- is it online somewhere? I tried to find it the other day, but I couldn't.

**Comment by kugel-** [comment]
It's in geany's tree under scripts, but it's incomplete since it misses a lot of deps. I'm working on it though

**Comment by codebrainz** [comment]
Ah, right under my nose the whole time :)  Thanks @kugel-

**Comment by eht16** [comment]
See also #311
