### ISSUE TITLE
Doesn't and isn't are not proper English?

### ISSUE THREAD

**Issue by prahladyeri** [geany/geany-plugins#320]
Both US & UK English spell-checks highlight these two words as incorrect. But I happen to know that they are correct. However, I'm not sure this is a bug in this geany-plugin or the source of these language packs itself in `ubuntu 14.04`. Please provide any suggestions.

**Comment by eht16** [comment]
#322 should fix the issue. I'd be happy to get any feedback if you could test the changes.

The reason for the previous behaviour is that the Spellcheck plugin splitted words to be checked also at the ' (single quote). I changed the code to consider the single quote as part of a word, and so the spell checker performs on the word "doesn't" instead of the two words "doesn" and "t".
