### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by CoWayger** [geany/geany-plugins#420]
After running ./autogen.sh & installing intltool installation crashes:

You should add the contents of '/usr/share/aclocal/intltool.m4' to 'aclocal.m4'.
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I build/cache -I build -I build/bundled -I geanypy/m4 --install
build/i18n.m4:20: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
aclocal: installing 'build/cache/nls.m4' from '/usr/share/aclocal/nls.m4'
aclocal: installing 'build/cache/pkg.m4' from '/usr/share/aclocal/pkg.m4'
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:15: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:16: error: possibly undefined macro: AC_PROG_LIBTOOL
configure:5255: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
autoreconf: /usr/bin/autoconf failed with exit status: 1

Any better method to install it?

**Comment by frlan** [comment]
Which system are you using?

**Comment by CoWayger** [comment]
Hello, I'm trying to get newer geany than 1.23.1 on Linux Mint 17.3 Rosa. I'm up to plugin http://plugins.geany.org/pairtaghighlighter.html. Which I very miss. Thank you for help. 

I tried to install newer geany from deb compiled, but this leads to depencedcy conflicts.

**Comment by frlan** [comment]
You need to install libtool at least.

**Comment by b4n** [comment]
You'll need libtool and libglib-2.0-dev (and libgtk-2.0-dev too, but that will "only" be required for actually running configure).

Note that you do not need any of those to get proper error messages stating the dependencies if you use the release tarballs instead of the Git repository.  I'm not saying it's better to use the tarball per se, just that it's more targeted at users -- although most users will use their distribution's packages anyway.

**Comment by b4n** [comment]
The best we could do for this would be altering autogen.sh so it'd check for what is needed for autoreconf to run properly.  I would have thought it was a waste of effort because only power users would try and build from Git, but apparently that's not so right.  So maybe it's something we should try and do?

**Comment by LarsGit223** [comment]
@CoWayger: did you manage to compile geany-plugins? Maybe try the current version. Or should we close this issue?

**Comment by CoWayger** [comment]
Hello, I upgraded to Mint 19.2, there is no such problem on this distro,
you can close this issue.

st 15. 5. 2019 v 21:05 odesílatel LarsGit223 <notifications@github.com>
napsal:

**Comment by elextr** [comment]
@CoWayger Just a note, if you are the originator you can close it yourself.
