### ISSUE TITLE
[addons] Mark all only when word selected

### ISSUE THREAD

**Issue by thdoan** [geany/geany-plugins#445]
In most code editors when you unselect the word, all the highlighted marks are also cleared. I wish the mark all functionality in this plugin would also behave like this. Currently you have to either double-click on a blank line or manually clear marks.

**Comment by chamfay** [comment]
Unselected with single click!

**Comment by eht16** [comment]
@thdoan what exactly do you mean by `when you unselect the word`?
Do you want to unselect with a single click as well?

For the record, you can also unselect a previous mark all selection by double clicking the same word again.

**Comment by thdoan** [comment]
@eht16 "when you unselect the word" means when you click anywhere on the screen to clear the text selection.

**Comment by eht16** [comment]
I implemented the requested feature in #481.
Single click deselect is configurable and disabled by default.

Due to the fact, that the plugin has to differentiate single and double clicks (technically a double click is just a sequence of two single clicks in a short time), there is a slow delay in deselecting after the click. This delay is about 250ms for GTK2 and about 400ms for GTK3 (default values).
This is not ideal but I didn't find a better solution.

Any feedback is welcome.

**Comment by thdoan** [comment]
@eht16 Thanks, that is better than finding a blank line to double-click on :).

**Comment by eht16** [comment]
I actually found a better way: now the highlight is removed instantly on click as expected. Instead the double click to create a new highlight is delayed by 50ms. This is enough to differentiate between the events but not really noticeable by the user.
