### ISSUE TITLE
Remove references to Gtk internals

### ISSUE THREAD

**Issue by frlan** [geany/geany-plugins#504]
Inside #478 we recognized that Treebrwoser is using direct access to internal things of Gtk. This is very likely to break at some point and needs to be fixed.

**Comment by LarsGit223** [comment]
I think this can be closed. I checked all Gtk function calls and found them all with a search on the GNOME developer center page. I think this functions are confusing maybe:
```
gtk_tree_store_iter_clear_nodes
_gtk_cell_layout_get_cells
```
These will not be found in the Gtk API because they are part of ```treebrowser.c```. IMHO there are no references to Gtk internals but some bad naming. Or did I oversee something?
