### ISSUE TITLE
[Split Window] View menu options don't affect right side split

### ISSUE THREAD

**Issue by BobCollins42** [geany/geany-plugins#600]
The menu options 
View -> Show Markers Margin
View -> Show Line Numbers
don't control the respective items on the right side split.

You can "unsplit," set the options, and then split again and the new window has the proper appearance.

**Comment by pcsanza** [comment]
I see the same thing except I am splitting top and bottom.  I don't need to "unsplit", though - I can click the arrow on the split bar to force showing the current document in the split window (even if that is the document already in the split window) this will force the options (such as show spaces or line numbers) to show up in the split window. However some things refuse to work in the 2nd window no matter what I do - such as autoindent.

**Comment by elextr** [comment]
The split window is best treated as a read-only view, its does not provide full editing capability.  Geany is designed knowing about only one edit window, a plugin may add another editing window, but cannot change the design of Geany.  So operations that are part of the editing widget work, since it _is_ the extra window, those operations that are part of Geany do not work since Geany is not written to handle extra edit windows.

There have been several attempts to fix this over the years, but they were either very large changes, or had poor performance (@b4n has GTK3 speed improved for your window switch hack yet?) or were otherwise unacceptable.

**Comment by elextr** [comment]
Closed as on wrong repository and passage of time
