### ISSUE TITLE
[treebrowser] no more icon for html files

### ISSUE THREAD

**Issue by brunob** [geany/geany-plugins#657]
Since a recent update, running geany 1.30.1, the panel doesn't show any icon for html files : 

![treebrowser](https://user-images.githubusercontent.com/418064/33839154-ce496aec-de91-11e7-9a7b-a802a435099c.png)

Tested with different icons sets on ubuntu 16.04 on unity. Strangely the documents panel show these icons.

**Comment by LarsGit223** [comment]
I can confirm the problem with Ubuntu 16.04 and an actual version of geany (built from git master). Like the documents panel, the file browser plugin is showing the icon for the .html file.

**Comment by elextr** [comment]
@LarsGit223 are you missing a not?  The two sentences seem to contradict, did you mean "can not confirm" or "is not showing"?

**Comment by codebrainz** [comment]
The icons come from the icon theme, they aren't provided by Geany (or plugins). Either your theme is missing them or there is a problem with the mime-types database.

Works for me in KDE using Breeze icon theme.

**Comment by elextr** [comment]
Works in Mint Cinnamon 17 (@brunob you havn't said what desktop) which is based on Ubuntu 16.04, so I think @codebrainz point that the desktop setup is wrong, probably theme, I think most mime_types are the same across distros.

**Comment by LarsGit223** [comment]
@brunob: What I meant is that I can confirm that the icon is missing in the treebrowser panel but it is showing in the filebrowser panel.

I am using Ubuntu 16.04, gnome desktop, standard theme.

@codebrainz: what I wonder about is, that it works in one plugin but not in the other. The icon itself seems to be present in the theme otherwise it would be missing in all plugins. Or am I overseeing something?

**Comment by codebrainz** [comment]
@LarsGit223 dunno, but here's their code:

https://github.com/geany/geany-plugins/blob/1.32.0/treebrowser/src/treebrowser.c#L208

https://github.com/geany/geany/blob/1.32.0/plugins/filebrowser.c#L184

**Comment by brunob** [comment]
@elextr i've updated my comment, i'm using unity desktop, and as i said i've tested with default ubuntu icon theme and other ones.

> What I meant is that I can confirm that the icon is missing in the treebrowser panel but it is showing in the filebrowser panel.

+1 exactly the same here

**Comment by elextr** [comment]
@medovina ping

**Comment by b4n** [comment]
I see that the filebrowser code falls back to a plain text icon, would that be the reason?  Does the HTML files in filebrowser have a plain text icon?

Otherwise the code seems fairly similar, although filebrowser is probably simpler and better off without manually loading the icons.  If there's no strong reason to do it manually in treebrowser it could make sense to simplify the code and let GTK actually render the GIcon, which is not only simpler but also handles live theme changes and whatnot.

**Comment by LarsGit223** [comment]
@b4n: exactly, I'm preparing a PR right now.
