### ISSUE TITLE
GeanyCtags does not respect relative project base path.

### ISSUE THREAD

**Issue by van-de-bugger** [geany/geany-plugins#698]
Geany 1.32.

Preferences->General->Miscellaneous: "Project file is stored inside the project base directory" is checked. A project is open.

If project base path is absolute, everything works as expected. However, if project base path is `.`, "Generate tags" hangs.

I found that Geany does not hang actually, but waits for `ctags`. However, it indexes *not* the project directory but *current* directory (which intentionally or accidentally is my home directory). The current directory contains many projects, indexing it requires a lot of time.

While Geany is waiting for `ctags`, interface freezes. I would expect Geany builds index in background (like Geany builds the project), so user interface does not freeze.

**Comment by techee** [comment]
@van-de-bugger Sorry, didn't notice this report earlier.

The relative path problem should be fixed by #755. I actually wrote the code in the time I wrote https://github.com/geany/geany/pull/33 and expected to use the functionality from Geany - which never materialized.

Tag generation isn't running asynchronously because using Geany there's no way to get notified when it's finished so the plugin knows it can use the generated tags file. But it shouldn't be a problem when things work correctly (tag generation for huge projects like linux kernel takes about 20s and normal projects should take much less time).
