### ISSUE TITLE
Spellcheck not available with latest Arch Linux release.

### ISSUE THREAD

**Issue by arcmags** [geany/geany-plugins#728]
geany 1.33 (built on 2018-03-06 with GTK 3.22.28, GLib 2.54.3)
geany-plugins 1.33-1
aspell 0.60.6.1-5
enchant 2.2.3-1
hunspell 1.6.2-1
hunspell-en 2017.01.22-2
hunspell-en_US 2017.01.22-2
linux 4.15.8-1-ARCH

After a full system update, the Spellcheck plugin is no longer in the Plugin Manager dialog.

**Comment by frlan** [comment]
Thanks for reporting but I think you should report this to Arch itself at https://bugs.archlinux.org

**Comment by eht16** [comment]
This is only partly an issue with ArchLinux.
For the 1.33 release we can't do anything to fix it but for the future. Enchant bump their library version number recently including the pkgconfig name (`enchant` vs `enchant-2`) and so G-P's `configure` checks for the wrong package name.

I'll prepare a patch to support building against the new and old package name.

**Comment by y0uCeF** [comment]
I faced the same issue on Archlinux. I got this error when I forced --enable-spellcheck:
```
checking for enchant >= 1.5... no
checking for enchant >= 2.0... no
checking for enchant >= 1.3... no
configure: error: Package requirements (enchant >= 1.3) were not met:
No package 'enchant' found

```
Note that my current version is `enchant 2.2.3-1`
As a quick workaround, it is enough to install an enchant package which has the version number in the name (eg. enchant2). Such package exists in the AUR, unfortunately, with version 1.6. On the good side, it doesn't conflict with the main enchant package and geany's spellcheck is back (I assume it is using the 1.6 version since it was compiled based on it, please confirm this).  
Looking forward to the definitive fix for this problem.

**Comment by eht16** [comment]
#729 adds support for both the old and new Enchant package names and so should solve the issue for future releases.

For the current release, please ping the ArchLinux package maintainers to backport the patch.
