### ISSUE TITLE
vimode: can't enter command (manjaro os)

### ISSUE THREAD

**Issue by thewalldao** [geany/geany-plugins#941]
I can type a command but after i type command i want and press enter , nothing happen, it still in that command.
Ex: 
    :s/main/man/g
when i press enter , nothing happen and it still show:
    :s/main/man/g
Please help me. I want to use vimode very much .
Thank you very much.

**Comment by techee** [comment]
I'm really wondering what's going on - I can't duplicate the bug here. A few questions:
1. What GTK version is Geany built against? You can find it under Help->About.
2. Do you use some other plugins? Do you still experience this problem when you disable the plugins?
3. Do you use some non-English keyboard layout?

**Comment by attila-v** [comment]
hi,
my experience is that if I switch off the numlock on the keyboard, the geany will get the Enter from the textbox. But I do not know, what if I my 14" laptop has not got numlock key...

**Comment by techee** [comment]
Oh, that might be the problem - I test it on a notebook without numerical keyboard and numlock so I didn't see this. Will try it with an external keyboard.

**Comment by thewalldao** [comment]
> hi,
> my experience is that if I switch off the numlock on the keyboard, the geany will get the Enter from the textbox. But I do not know, what if I my 14" laptop has not got numlock key...

Thank you so much , now i can enter comand with switch off num lock, still don't know why this happen.
