### ISSUE TITLE
Spell check plugin does not update misspellings on changed text

### ISSUE THREAD

**Issue by TitusLabienus** [geany/geany-plugins#988]
I have installed and activated the spell check plugin. However, the misspellings get not updated automatically on modifying one's text. For example, if I type a misspelled word, it does not get marked with the red curly underline. The only way to get it marked is to switch the language, e.g. back and forth, or simply by clicking Tools -> Spell Check -> Default (en_GB) (assuming writing in English). Al new misspellings get only marked if I switch the spell check language again.

**Comment by eht16** [comment]
Let's begin with the obvious: did you enable the "Check spelling while typing" option in the plugin preferences?

**Comment by TitusLabienus** [comment]
Thank you, I was not aware of the plugin preferences. I think it wouldt be more intuitive though if the spell check was enabled by default when the plugin is enabled, and I guess that is the common use case. At least I would expect the spell check to run on typing by default, once I enable the plugin.

**Comment by eht16** [comment]
I think most users usually use Geany as code editor and only sometimes as text editor or for other uses where spell checking while typing is desired.
So, IMO the default is appropriate because users can enable "check while type" in cases where it is needed.

There is also a toolbar button to quickly toggle this option.
